FROM node:8.11.3 AS build-env
WORKDIR /usr/app
COPY package.json package-lock.json cli.js ./
RUN npm install --production


FROM gcr.io/distroless/nodejs
COPY --from=build-env /usr/app /usr/app
WORKDIR /usr/app
VOLUME /usr/app/android

CMD ["cli.js"]
